spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/cs
    username:  root
    password:  root
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  
    

mybatis:
  type-aliases-package: com.yeyu.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml 
  
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql